

services:

    nginx:
        depends_on:
            - wordpress
        image: nginx
        container_name: nginx
        build: ./requirements/nginx
        ports:
        -   "443:443"
        volumes:
            - Volumedata:/var/www/html
        networks:
        - wordpress_network
    wordpress:
        image: wordpress
        container_name: wordpress
        build: ./requirements/wordpress
        ports:
        -   "9000:9000"
        volumes:
            - Volumedata:/var/www/html
        networks:
        - wordpress_network
    

volumes:
    Volumedata:

networks:
  wordpress_network:
    driver: bridge
