

services:
    nginx:
        depends_on:
            - wordpress
            - website
        image: my_nginx
        container_name: nginx
        build: ./requirements/nginx
        restart: always
        ports:
        -   "443:443"
        volumes:
            - wp_files:/var/www/html/wordpress
            - my_profile:/var/www/html/website

        networks:
        - inception

    wordpress:
        depends_on:
            - mariadb
        image: my_wordpress
        container_name: wordpress
        build: ./requirements/wordpress
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - wp_files:/var/www/html/wordpress
        networks:
        - inception
    mariadb:
        image: my_mariadb
        container_name: mariadb
        build: ./requirements/mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
            - MYSQL_DATABASE=${MYSQL_DB}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASS}
        ports:
            - "3306:3306"
        volumes:
            - database:/var/lib/mysql
        networks:
        - inception
############### services bonus
    adminer:
        image: my_adminer
        container_name: adminer
        build: ./requirements/bonus/adminer
        ports:
            - "3000:3000"
        networks:
        - inception
    redis:
        depends_on:
            - wordpress
            - adminer
        image: my_redis
        container_name: redis
        build: ./requirements/bonus/redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - wp_files:/var/www/html/wordpress
        networks:
        - inception
    ftp:
        image: my_ftp
        container_name: ftp
        build: ./requirements/bonus/ftp
        restart: always
        ports:
            - "21:21"
            - "21100-21110:21100-21110"
        volumes:
            - wp_files:/var/www/html/wordpress
        networks:
        - inception
    website:
        image: my_website
        container_name: website
        build: ./requirements/bonus/website
        restart: always
        ports:
            - "4000:80"
        networks:
        - inception
    cadvisor:
        image: my_cadvisor
        container_name: cadvisor
        build: ./requirements/bonus/cadvisor
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8080:8080"
        networks:
        - inception


volumes:
    wp_files:
        driver: local
        driver_opts:
            type: none
            device: /home/abdelbassat/data/files/
            o: bind
    database:
        driver: local
        driver_opts:
            type: none
            device: /home/abdelbassat/data/database/
            o: bind
    my_profile: {}
    

networks:
  inception:
    driver: bridge
