

services:
    nginx:
        depends_on:
            - wordpress
            - website
        image: my_nginx
        container_name: nginx
        build: ./requirements/nginx
        restart: always
        ports:
        -   "443:443"
        volumes:
            - /home/abdelbassat/data/files:/var/www/html/wordpress
            - my_profile:/var/www/html/website

        networks:
        - inception

    wordpress:
        depends_on:
            - mariadb
        image: my_wordpress
        container_name: wordpress
        build: ./requirements/wordpress
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - /home/abdelbassat/data/files:/var/www/html/wordpress
        networks:
        - inception
    mariadb:
        image: my_mariadb
        container_name: mariadb
        build: ./requirements/mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
            - MYSQL_DATABASE=${MYSQL_DB}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASS}
        ports:
            - "3306:3306"
        networks:
        - inception
############### services bonus
    adminer:
        depends_on:
            - redis
        image: my_adminer
        container_name: adminer
        build: ./requirements/bonus/adminer
        restart: always
        networks:
        - inception
    redis:
        depends_on:
            - wordpress
        image: my_redis
        container_name: redis
        build: ./requirements/bonus/redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - /home/abdelbassat/data/files:/var/www/html/wordpress
        networks:
        - inception
    ftp:
        image: my_ftp
        container_name: ftp
        build: ./requirements/bonus/ftp
        restart: always
        ports:
            - "21:21"
            - "21100-21110:21100-21110"
        volumes:
            - /home/abdelbassat/data/files:/var/www/html/wordpress
        networks:
        - inception
    website:
        image: my_website
        container_name: website
        build: ./requirements/bonus/website
        restart: always
        volumes:
            - my_profile:/var/www/html/website
        networks:
        - inception


volumes:
  my_profile:


networks:
  inception:
    driver: bridge
